name: NBA Defense Data

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-defense:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install pandas requests lxml

      - name: Fetch defense ratings
        run: python fetch_nba_defense.py

      - name: Fetch DvP
        run: python fetch_dvp.py

      - name: Commit & Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update defense data" || echo "No changes"
          git push
