name: NBA Defense Data Fetch

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install pandas requests lxml beautifulsoup4

    - name: Fetch Defense Ratings
      run: python fetch_nba_defense.py

    - name: Fetch Defense vs Position
      run: python fetch_dvp.py

    - name: Commit and push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update NBA defense stats"
        git push
